export enum EIndividualLessonState {
    CLIENT_REQUESTED = 'CLIENT_REQUESTED',
    APPOINTMENT_ACCEPTED = 'APPOINTMENT_ACCEPTED',
    SCHOOL_REQUESTED = 'SCHOOL_REQUESTED',
    NEW_TIME_PROPOSED_BY_SCHOOL = 'NEW_TIME_PROPOSED_BY_SCHOOL',
    NEW_TIME_PROPOSED_BY_CLIENT = 'NEW_TIME_PROPOSED_BY_CLIENT',
    APPOINTED_AND_CANCELED_CORRECTLY = 'APPOINTED_AND_CANCELED_CORRECTLY',
    APPOINTED_AND_CANCELED_INCORRECTLY = 'APPOINTED_AND_CANCELED_INCORRECTLY',
    APPOINTMENT_DECLINED = 'APPOINTMENT_DECLINED',
    PASSED_AND_APPROVED_BY_SCHOOL = 'PASSED_AND_APPROVED_BY_SCHOOL',
    PASSED_AND_APPROVED_BY_CLIENT = 'PASSED_AND_APPROVED_BY_CLIENT',
    PASSED_AND_APPROVED_BY_ALL = 'PASSED_AND_APPROVED_BY_ALL',
    PASSED_WITH_FORCED_MONEY_WITHDRAWAL = 'PASSED_WITH_FORCED_MONEY_WITHDRAWAL',
    PASSED_WITHOUT_MONEY_WITHDRAWAL = 'PASSED_WITHOUT_MONEY_WITHDRAWAL'
}
