export enum EIndividualLessonActions {
    ACCEPT_APPOINTMENT = 'ACCEPT_APPOINTMENT',
    PROPOSE_NEW_TIME = 'PROPOSE_NEW_TIME',
    DECLINE_APPOINTMENT = 'DECLINE_APPOINTMENT',
    CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT',
    APPROVE_APPOINTMENT_PASSED = 'APPROVE_APPOINTMENT_PASSED',
    SET_PASSED_WITH_FORCED_MONEY_WITHDRAWAL = 'SET_PASSED_WITH_FORCED_MONEY_WITHDRAWAL',
    SET_PASSED_WITHOUT_MONEY_WITHDRAWAL = 'SET_PASSED_WITHOUT_MONEY_WITHDRAWAL',
    DELETE = 'DELETE',
    UPDATE_BASIC_FIELDS = 'UPDATE_BASIC_FIELDS',
    UPDATE_START_TIME = 'UPDATE_START_TIME'
}
